worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  charset utf-8;
  default_type application/json;
  server_tokens off;

  proxy_connect_timeout 70;
  proxy_send_timeout 70;
  proxy_read_timeout 70;
  send_timeout 70;

  client_header_buffer_size 8k;
  large_client_header_buffers 4 16k;
  merge_slashes off;

  server {
    listen 80;
    server_name localhost;

    location = / {
      default_type text/html;
      root /etc/nginx/html;
      try_files /index.html =404;
    }

    location = /index.html {
      default_type text/html;
      root /etc/nginx/html;
    }

    location = /api/2/things {
      proxy_pass                    http://api:8000/api/ditto/things;
      proxy_http_version            1.1;
      proxy_set_header              Host                      $http_host;
      proxy_set_header              X-Real-IP                 $remote_addr;
      proxy_set_header              X-Forwarded-For           $proxy_add_x_forwarded_for;
      proxy_buffering               off;
    }

    location /api {
      proxy_pass                    http://ditto-gateway:8080;
      proxy_http_version            1.1;
      proxy_set_header              Host                      $http_host;
      proxy_set_header              X-Real-IP                 $remote_addr;
      proxy_set_header              X-Forwarded-For           $proxy_add_x_forwarded_for;
      proxy_set_header              x-ditto-pre-authenticated "nginx:ditto";
      proxy_set_header              Connection                '';
      chunked_transfer_encoding     off;
      proxy_buffering               off;
      proxy_cache                   off;
    }

    location /ws {
      proxy_pass                    http://ditto-gateway:8080;
      proxy_http_version            1.1;
      proxy_set_header              Host                      $http_host;
      proxy_set_header              x-ditto-pre-authenticated "nginx:ditto";
      proxy_set_header              Upgrade                   $http_upgrade;
      proxy_set_header              Connection                "upgrade";
      proxy_read_timeout            1d;
      proxy_send_timeout            1d;
    }

    location /health {
      proxy_pass                    http://ditto-gateway:8080/health;
      proxy_http_version            1.1;
      proxy_set_header              Host                      $http_host;
    }

    location /status {
      proxy_pass                    http://ditto-gateway:8080/overall/status;
      proxy_http_version            1.1;
      proxy_set_header              Host                      $http_host;
    }
  }
}
